// BYTE-INVARIANCE — adding the OPTIONAL `x402_payment_ref` member changes
// ZERO bytes of any receipt that does not set it (docs/spec/delivery-proof.md
// §7). This is the claim the whole "additive, no version bump" argument rests
// on, so it is proved by frozen literals, not by reasoning.
//
// METHOD. The expected values below were generated by running this exact
// construction (fixed 32-byte seed, fixed session id, fixed timestamps, fixed
// event bodies) against the commit BEFORE `x402_payment_ref` existed, and
// pasted in verbatim. Nothing in this file recomputes them from the current
// implementation, so if the field ever perturbs the canonical bytes — a
// reserved slot, a null placeholder, an eagerly-assigned `undefined` — the JCS
// string, the entry_hash, and the Ed25519 signature all diverge here and this
// test fails. A green run is a byte-for-byte match against pre-change output.
//
// The signature is included deliberately: it is the sharpest possible witness,
// since Ed25519 over even a one-byte-different preimage produces completely
// different bytes.

import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import {
  Chain,
  argsHash,
  contentOf,
  ed25519PrivateKeyFromSeed,
  entryHashOfCanonical,
  formatVerifyResult,
  genesisPrevHash,
  jcsBytes,
  makeKid,
  publicKeyFromPrivate,
  resultHash,
  runVerify,
  type LoadedFullIdentity,
  type ShellEvent,
} from "../src/vendor/recorder/index.js";
import { appendReceipt } from "../src/receipt.js";

const SEED = Buffer.alloc(32, 7);
const SESSION = "byte-invariance-session";
const TS0 = "2026-01-01T00:00:00.000Z";
const TS1 = "2026-01-01T00:00:01.000Z";

// ---- FROZEN pre-change output (generated on the commit before the field) ----
const EXPECTED_GENESIS =
  "sha256:d6985da368f61e53e984a401530ecf986a71a160f4fcbadc139a4d3a84718ad6";

const EXPECTED_CHAIN = [
  {
    jcs: '{"agent":{"vendor":"chirindo-test","version":"0.0.0"},"event":{"args_hash":"sha256:43258cff783fe7036d8a43033f830adfc60ec037382473548ac742b888292777","decision":"allow","decision_source":"config","outcome":"executed","result_hash":"sha256:a7324f62484109d5cf863b4a722634c676275f8c24b74d2828ccb3e6e8e7ae50","server":"everything","tool_name":"echo","type":"mcp_call"},"gate":null,"iss":"urn:chirindo:key:--6IM5l0OosLj9yWskISYhUA3n_3CURQkmrYMSha_ck","key_thumbprint":"--6IM5l0OosLj9yWskISYhUA3n_3CURQkmrYMSha_ck","kid":"--6IM5l0OosLj9yWskISYhUA3n_3CURQkmrYMSha_ck","prev_hash":"sha256:d6985da368f61e53e984a401530ecf986a71a160f4fcbadc139a4d3a84718ad6","request_commitment":"sha256:a41f21cdbf0539c2377f7087a288d5040bf987c44c7ad1060b9c7f7e6caeb157","seq":0,"session_id":"byte-invariance-session","ts":"2026-01-01T00:00:00.000Z","v":"evidence.action/1"}',
    entry_hash:
      "sha256:2309fbdea34b9f311b78ece1f3c745a20fb6019884fea1b514cfb9568813c3df",
    sig: "48xgowLTFQixQSXQg_l-wb824WoZRbhvFYb7-lYhzDcnWCTtnl7dIMXs5BmOEG4dutmfQSu23A9A3QBNf59TBA",
  },
  {
    jcs: '{"agent":{"vendor":"chirindo-test","version":"0.0.0"},"event":{"argv":["ls","-la"],"cwd":"/tmp","exit_code":0,"outcome":"executed","type":"shell"},"gate":null,"iss":"urn:chirindo:key:--6IM5l0OosLj9yWskISYhUA3n_3CURQkmrYMSha_ck","key_thumbprint":"--6IM5l0OosLj9yWskISYhUA3n_3CURQkmrYMSha_ck","kid":"--6IM5l0OosLj9yWskISYhUA3n_3CURQkmrYMSha_ck","prev_hash":"sha256:2309fbdea34b9f311b78ece1f3c745a20fb6019884fea1b514cfb9568813c3df","request_commitment":"sha256:4976d1776c5aec4918b35d7e3501bb29309c7c873a0ed2a2c4bb07ace92acbf1","seq":1,"session_id":"byte-invariance-session","ts":"2026-01-01T00:00:01.000Z","v":"evidence.action/1"}',
    entry_hash:
      "sha256:dca3eb2cbb766418755f180ffde29f6dff8b0df163f146643465863b08e19b4c",
    sig: "Xw0uClqSen7Yl_yoYWrRYDl9mLxejwWQtSb8_wL7Or2P7Y8477gOz8GFmpIp9b7X8OnO5AxfVk7lER2vdcIoAw",
  },
];

const EXPECTED_RECEIPT = {
  jcs: '{"agent":{"vendor":"chirindo","version":"0.0.1"},"event":{"args_hash":"sha256:43258cff783fe7036d8a43033f830adfc60ec037382473548ac742b888292777","decision":"allow","decision_source":"config","outcome":"executed","result_hash":"sha256:a7324f62484109d5cf863b4a722634c676275f8c24b74d2828ccb3e6e8e7ae50","server":"everything","tool_name":"echo","type":"mcp_call"},"gate":{"gate_family":"permit","gate_receipt":"sha256:f728885ede25d992334b2e126cf217aead61eba4b5969d91110bd65ab7fedeba","request_commitment":"sha256:a41f21cdbf0539c2377f7087a288d5040bf987c44c7ad1060b9c7f7e6caeb157","result":"act"},"iss":"https://example.test","jwks_uri":"https://example.test/.well-known/jwks.json","key_thumbprint":"--6IM5l0OosLj9yWskISYhUA3n_3CURQkmrYMSha_ck","kid":"--6IM5l0OosLj9yWskISYhUA3n_3CURQkmrYMSha_ck","prev_hash":"sha256:d6985da368f61e53e984a401530ecf986a71a160f4fcbadc139a4d3a84718ad6","request_commitment":"sha256:a41f21cdbf0539c2377f7087a288d5040bf987c44c7ad1060b9c7f7e6caeb157","seq":0,"session_id":"byte-invariance-session","ts":"2026-01-01T00:00:00.000Z","v":"evidence.action/1"}',
  entry_hash:
    "sha256:ade20e84628c8686e0e61be75842177c18f2c98de83be3b9554573e67c94117c",
  sig: "Rb-i53HyEANkkDvR9_jAze9f8JtpW_KYJWK1R3h-OfYXUxD0iRNBn4RPkL6EawqQW8WgMez2MErg7AXBGrj8Bg",
};
// ---------------------------------------------------------------------------

function deterministicIdentity(): LoadedFullIdentity {
  const privateKey = ed25519PrivateKeyFromSeed(SEED);
  const publicKey = publicKeyFromPrivate(privateKey);
  return { kid: makeKid(publicKey), publicKey, privateKey } as LoadedFullIdentity;
}

describe("byte-invariance: absent x402_payment_ref changes nothing (spec §7)", () => {
  it("genesis prev_hash is untouched", () => {
    expect(genesisPrevHash(SESSION)).toBe(EXPECTED_GENESIS);
  });

  it("Chain.append produces the pre-change bytes, entry_hashes and signatures", () => {
    const { kid, privateKey } = deterministicIdentity();
    const chain = new Chain({
      sessionId: SESSION,
      agent: { vendor: "chirindo-test", version: "0.0.0" },
      kid,
      privateKey,
    });
    const records = [
      chain.append(
        {
          type: "mcp_call",
          outcome: "executed",
          server: "everything",
          tool_name: "echo",
          args_hash: argsHash({ b: 2, a: 1 }),
          result_hash: resultHash({
            content: [{ type: "text", text: "hi" }],
            isError: false,
          }),
          decision: "allow",
          decision_source: "config",
        },
        TS0,
      ),
      chain.append(
        {
          type: "shell",
          outcome: "executed",
          argv: ["ls", "-la"],
          cwd: "/tmp",
          exit_code: 0,
        },
        TS1,
      ),
    ];

    records.forEach((r, i) => {
      const canon = jcsBytes(contentOf(r));
      expect(canon.toString("utf8")).toBe(EXPECTED_CHAIN[i]!.jcs);
      expect(entryHashOfCanonical(canon)).toBe(EXPECTED_CHAIN[i]!.entry_hash);
      expect(r.sig).toBe(EXPECTED_CHAIN[i]!.sig);
      // The key must not appear anywhere in the canonical form.
      expect(canon.toString("utf8")).not.toContain("x402_payment_ref");
    });
  });

  it("appendReceipt (the gate's emission path) produces the pre-change bytes", () => {
    const identity = deterministicIdentity();
    const dir = mkdtempSync(join(tmpdir(), "chirindo-bi-"));
    try {
      const record = appendReceipt({
        chainPath: join(dir, "chain.jsonl"),
        sessionId: SESSION,
        identity,
        server: "everything",
        toolName: "echo",
        toolArgs: { b: 2, a: 1 },
        toolResult: { content: [{ type: "text", text: "hi" }], isError: false },
        jwksUri: "https://example.test/.well-known/jwks.json",
        decision: { kind: "allow" },
        ts: TS0,
      });
      const canon = jcsBytes(contentOf(record));
      expect(canon.toString("utf8")).toBe(EXPECTED_RECEIPT.jcs);
      expect(entryHashOfCanonical(canon)).toBe(EXPECTED_RECEIPT.entry_hash);
      expect(record.sig).toBe(EXPECTED_RECEIPT.sig);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("the pre-existing legacy v0 golden chain still verifies, with delivery none", () => {
    const dir = resolve(import.meta.dirname, "fixtures", "legacy-v0");
    const result = runVerify({
      chainPath: join(dir, "chain.jsonl"),
      identityPath: join(dir, "identity.json"),
    });
    expect(result.kind).toBe("valid");
    if (result.kind !== "valid") return;
    // A v0 receipt has no payment ref, so the delivery logic is never entered
    // and its output line is exactly what it was before this feature.
    expect(result.delivery).toBe("none");
    const formatted = formatVerifyResult(result);
    expect(formatted.line).not.toContain("DELIVERY");
    expect(formatted.exitCode).toBe(0);
  });

  it("setting the field DOES change the bytes — invariance holds only while absent", () => {
    const { kid, privateKey } = deterministicIdentity();
    const event: ShellEvent = {
      type: "shell",
      outcome: "executed",
      argv: ["ls", "-la"],
      cwd: "/tmp",
      exit_code: 0,
    };
    const withRef = new Chain({
      sessionId: SESSION,
      agent: { vendor: "chirindo-test", version: "0.0.0" },
      kid,
      privateKey,
    }).append(event, TS0, {
      x402PaymentRef: "sha256:" + "0".repeat(64),
    });
    const canon = jcsBytes(contentOf(withRef)).toString("utf8");
    expect(canon).toContain('"x402_payment_ref":"sha256:');
    expect(canon).not.toBe(EXPECTED_CHAIN[1]!.jcs);
  });
});
